### ISSUE TITLE
Creating incorrect IN clause with numeric values

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#163]
When requesting data from a service with an IN clause using numeric values for a string column the SQL-Statement is broken.
This is because in [MY_Database.in](https://github.com/Indicia-Team/warehouse/blob/master/application/libraries/MY_Database.php#L53) there is a check if the value is numeric, but there is no check if the column is numeric.

I see to ways to solve this:
  1. check the type of the queried columns
  1. add a type definition to the request

Also all parameters in a IN clause must be of the same type. 
Example:
```
Request url: /index.php/services/data/location

Request parameters: [query={"in":["code",["DE","17498","MV"]]}, view=detail, mode=xml]

Error:
LINE 4: AND ("detail_locations"."code" IN ('DE',17498,'MV'))
                                       ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. - SELECT "detail_locations"."id", "detail_locations"."name", "detail_locations"."code", "detail_locations"."comment", "detail_locations"."parent_id", "detail_locations"."parent", "detail_locations"."centroid_sref", "detail_locations"."location_type_id", "detail_locations"."centroid_sref_system", st_astext(detail_locations.centroid_geom) as centroid_geom, st_astext(detail_locations.boundary_geom) as boundary_geom, st_astext(detail_locations.geom) as geom, "detail_locations"."external_key", "detail_locations"."created_on", "detail_locations"."created_by_id", "detail_locations"."created_by", "detail_locations"."updated_on", "detail_locations"."updated_by_id", "detail_locations"."updated_by", "detail_locations"."website_id", "detail_locations"."public"
FROM detail_locations
WHERE ("detail_locations"."website_id" IN (2) OR "detail_locations"."website_id" IS NULL)
AND ("detail_locations"."code" IN ('DE',17498,'MV'))
```

**Comment by johnvanbreda** [comment]
1. Checking the type of the queried columns is not easy because we are just overriding the kohana database.php file's in function so can't control what information is available. We don't actually know the database table the column is coming from so finding out the data type is tricky.
2. We could perhaps force you to submit the parameters like query={"in":["code",["DE","17498::text","MV"]]} to let the Data Services know that the parameter must be treated as a string. It's a possibility but if we can automate the solution to this issue it would be preferable as it makes the API easier to learn.
3. An alternative to 2 would be to manually include quotes around the number (i.e. query={"in":["code",["DE","'17498'","MV"]]}) - the Data Services code could then skip addition of the quotes since they are already there. The problem with this approach is that you can no longer search for strings that are actually wrapped in quotes in the database. 
4. Another idea - we could automatically quote ALL the parameters including those which pass the is_numeric test. From a few tests on PGAdmin using EXPLAIN ANALYZE it appears to not cause any performance hit, e.g. the following queries both have the same cost:

   - select * from locations where id in (10,20,30,40,50)
   - select * from locations where id in ('10','20','30','40','50')

   Although there will probably be a small hit on the CPU to do the conversion, it will be tiny and offset  by the fact that the PHP code will be a tiny bit simpler.

Any thoughts on option 3 and 4?

**Comment by dve** [comment]
We have discussed the options and our conclusion is option 4 since it does not need any changes in the usage of the api. If we should notice any performance impact because of the casts we can still consider option 2 or 3.
