### ISSUE TITLE
Where to get the warehouse?

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#182]
Hi,
I tried to install the warehouse, but where to get the code from?

The releases-archives on github are missing the sub projects (client_helpers, etc), the link on read-the-docs points to google-code which redirects to a non-existing github page.

Is checking out per git the preferred way even for non develpoing cases? Then the docs must be changed.

**Comment by JimBacon** [comment]
I would direct users to www.indicia.org.uk/downloads to obtain the code.

This currently links to a specific release, 1.3.0 which does include the sub-modules. It would be more maintainable if it linked to https://github.com/Indicia-Team/warehouse/releases so that it always showed the latest release.

The latest release is shown as 1.4.0 and, as reported, this does not include sub-modules. Our documentation at http://indicia-docs.readthedocs.io/en/latest/developing/github.html is currently lacking a procedure for making a release.

There is a more recent version, 1.5.0 which has not been tagged or released.

**Comment by johnvanbreda** [comment]
I've just released 1.6.0 at https://github.com/Indicia-Team/warehouse/releases/tag/v1.6.0 and have uploaded a complete zip file. I've also pointed the link on www.indicia.org.uk/downloads to the latest release at all times.
