### ISSUE TITLE
Problem with CUD status in scheduled tasks causing missing species alerts

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#229]
The background to this is that I had received a report of a species alert that hadn't arrived. Jim informed me the warehouse had been down, but under further investigation he found that the species alert in question wouldn't arrive even after the backlog was cleared.
Jim also found out that actually the problem could occur even if the server hadn't gone down.
We know the issue affects species alerts, but whether there are any other areas affected that use the CUD status is unknown.

The problem is essentially this (using the example of the species alerts). The CUD status is Created, Updated or Deleted. The problem with this is that if a record is created, then updated (such as verified) before the records are processed, it is marked as Updated and the Alert On Verification is sent because it is never marked as a Created record at the point the processing takes place.

My own personal thought is to fix this at the point of the CUD status rather than in the species alerts because what the species alerts is doing is logical given the status it is looking at.
Also if fixed at the CUD status point, other areas may benefit.
I would have thought that using separate flags might be more elegant, but that might be more fiddly to fix? So how about an extra CUD status to indicate a record has been Created and then Updated before the processing has occurred?

**Comment by JimBacon** [comment]
A couple of notes to add further information.

The warehouse was not down, it was just that scheduled tasks had stopped running so there were a backlog of records to process.

My full explanation goes as follows (inferred only from reading the code):
Say you have records that have been created and not processed over a long enough period that some of them have also been updated. If I list them in order of updated_on they look like this
```
        id  Created_on   Updated_on
  1      1    10:00        10:00
  2      4    10:03        10:03
…       …
199      3    10:02        11:59
200    201    12:00        12:00
201      2    10:01        12:01
```
If scheduled tasks were last run at 09:50 and I now run them at 12:30 what happens is that the first two hundred are processed. All these records have been created since scheduled tasks last ran and get a CUD status of C for created , including record id 3 which has also been updated. After this run of scheduled tasks last_scheduled_task_check is saved as 12:00
 
Next time scheduled tasks runs, record id 2 is top of the ordered list to be processed but, because its created_on time is prior to the last_scheduled_task_check it is seen as an updated record and not a new one and gets a CUD status of U.

Thus record id 3 never gets any update tasks processed and record id 2 never gets any create tasks processed.

This situation could occur even when scheduled tasks is running properly if, for example, there is a big upload of data which creates a delay in processing.

**Comment by andrewvanbreda** [comment]
Yes sorry I meant the scheduled tasks were down.
John go by Jim's explanation rather than mine as it is better.

I am a bit confused by the way this works so I don't think your explanation is quite the same as what I thought.
You said that 
"All these records have been created since scheduled tasks last ran and get a CUD status of C for created , including record id 3 (AVB row 199) which has also been updated."

Does that mean that ID 3 is marked as a "C" even though it has been updated and is then never processed as an Update at all because the processor next time moves onto record 201 (ID2) next time the processing runs?
Sorry, I don't know the ins and outs of how this works, or at least I might of known at some point and have now forgotten

**Comment by JimBacon** [comment]
I agree that the fix should be in application/controllers/scheduled_tasks.php.
As an alternative, I wonder if building the occdelta table from a union of two queries, one for creates and one for updates, would be simpler. The associated timestamps would be created_on and updated_on respectively.
That might be very nearly backwards compatible with modules using the CUD status and timestamp. Species alerts might have to get rid of the Distinct in the selection of $newOccDataForSpeciesAlert to allow for the case when occdelta contains a create and an update for the same record.

**Comment by andrewvanbreda** [comment]
Yes I agree something like that, I was just writing a message to say we need to handle the created_ons and updated_ons separately.
At the moment I think the code is vulnerable to failure because we are interested in both the created_ons and the updated_ons, but it is moving along the records based on the updated_on

**Comment by andrewvanbreda** [comment]
Do we need to get rid of that distinct? If a record now appears twice in occdelta because it has a create and update then won't those two lines have different CUD statuses? One would be C and the other U? so the lines would be different in occdelta

**Comment by JimBacon** [comment]
I think you are right. No need to change species alerts after all.

**Comment by andrewvanbreda** [comment]
I think I like the idea of fixing it in occdelta in theory. That last scheduled tasks run date is saying we have processed everything up to that date, which would be ok, I think the actual issue is that we haven't completed processing up to that date. So I think the problem is we are not creating the correct records to process, which is where occdelta and your solution comes in, although John may have other ideas.

We will need to make sure the code that is only expecting one row per record in occdelta still works though, that may be a sticking point, maybe using a distinct that excludes the CUD status.

**Comment by johnvanbreda** [comment]
I'm just picking this up - I'll review the other modules which use occdelta to judge if the proposed solution will work.

**Comment by johnvanbreda** [comment]
The following list notes which use the occdelta table, with comments relating to whether having both a C and U entry in occdelta for a single record will have side-effects:

- Autoverify - could generate IDs in the subquery output which I don't think will make any difference. Adding a distinct to the subquery (line 41) will fix this.
- Data cleaner - there is already a distinct on the insert into occurrence comments so the output should be OK. However I am slightly concerned that duplication of the IDs will cause a doubling up of the cost of the query, since presumably the distinct operation will be applied towards the end of query processing. This could probably be fixed by selecting distinct into another temp table first (which would be a very fast operation). 
- Species_alerts - already filters to CUD=C so the change benefits the module.
- Verifier notifications - this module only cares about zero vs non-zero counts, so duplicating records won't cause any problems.

**Comment by johnvanbreda** [comment]
I've a better fix (I think). The problem with the proposed fix is that the tracking of which records to process is based on the updated_on flag. So without an additional tracking of the last processed record on the bases of created on, we can't easily determine the block of created records to include. Adding additional tracking gets quite messy. I'm also aware that the purpose of the U flag is to indicate a change to something that has already been processed, not to indicate that a record has been created and then immediately changed (in which case we can just process the latest copy of the record and not worry about the 2 entries in occdelta). Effectively we just want 1 copy in occdelta for each record that has been created or changed, with U indicating where the processing tool will need to update existing work, and C indicating a new record it has not seen before.

My proposed solution is to change the way the timestamp is worked out, which is currently the latest edit (or creation) timestamp associated with the record. We use this to sort the records into processing order. If we work out the timestamp using the created timestamp of the record for all records that are new otherwise use the updated timestamp, then we will effectively make the editing of records that haven't yet been processed irrelevant - they will just come through the system as a single 'C'.

In Jim's example, the sort order will be different:
```
        id  Created_on   Updated_on
  1      1    10:00        10:00
  2      2    10:01        12:01
…       …
199      3    10:02        11:59
200      4    10:03        10:03
201    201    12:00        12:00
```

So, record 201 is correctly shunted to the end of the list. If we imagined the same scenario, but with a record that had been created at 09:00 and already processed, then edited at 10:02, you get the following:

```
        id  Created_on   Updated_on
  1      2    10:00        10:00
  2      3    10:01        12:01
…       …
198      1    09:00        10:02
199      4    10:02        11:59
200      5    10:03        10:03
201    201    12:00        12:00
```
You can see how the updated_on takes over as the sortable value for previously created records.

Hope that makes sense. We also won't need any module updates which is nice. I'm working on this now and just posting this here in case you have any comments (or I forget my plan!)

**Comment by johnvanbreda** [comment]
@JimBacon @andrewvanbreda I've created a pull request so you can review/test the proposed change before it is committed.

**Comment by JimBacon** [comment]
I like this but I think it requires an update to the species alert module. 

Where a record has been created and then verified before being processed by scheduled tasks it will now have a CUD status of 'C' and a record status of 'V'. It needs to trigger both 'verified' and 'entered' alerts. 

The current logic, in both the select query and the creation of notifications, assumes either a CUD status of 'C' or a CUD status of 'U' with a record status of 'V' and that only one notification needs to be triggered, not two.

**Comment by andrewvanbreda** [comment]
Hi,

Yes I believe Jim is correct, the proposed solution will not send the correct species alerts currently. 
I could change it so that it sends two notifications if "C" and "V" status is found, that wouldn't be hard.

But are we clear that the proposed solution is clear going forward for any new code that might use CUD.
The problem is at the moment I think we are saying "C" when it is created and updated and also for when it is created. 
I am not sure this is all that clear, I don't think that "C" is now an accurate representation of the information that CUD is trying to provide.
This could be a problem if we forget the logic just discussed for any new code in the future.

Wouldn't it be better to include an extra "CUD" status for the created/updated rows?
That way we know we can trust that status as being accurate, for instance a new programmer might not of been aware of our conversation

**Comment by JimBacon** [comment]
I see your point but John's solution is pretty neat and you would have to have a fair amount of knowledge if you were going to use this field in this table.

What if if we document it (at http://indicia-docs.readthedocs.io/en/latest/developing/warehouse/plugins.html#scheduled-task-hook ?) in which case we can give an accurate description. Comments in the code are always a good thing too!!!

**Comment by johnvanbreda** [comment]
See 24092581a9e50869f84a9708264768d9a0670fd7. I've implemented this solution. 

Regarding Andy's comment, the occdelta table CRUD action should be interpreted as the overriding change for the record within the context of this batch. In otherwords, if since the last scheduled task run, a record has been deleted, then you should only be told if the record was deleted and don't need to be told about any preceding updates. Likewise if a record was created since the last run, you only need to be told about the create event, not any following updates. This is the most efficient way of telling modules just enough information so that they are aware of the latest version of the record without generating extra information (leading to additional unwanted processing). For example, the data cleaner record only needs to know that a record has had a modification (create or update) so it can re-run the tests. Multiple entries in occdelta would have to be cleaned up. None of the existing usages of occdelta would benefit from having 2 entries in occdelta, one for the create and one for the update when a record is created then updated before being processed. 

I agree with improving the docs to explain this - I'll do that now.

Any reasons not to commit this now?

**Comment by JimBacon** [comment]
Looks ok from inspection. No other issues spring to mind. Some test scripts for Travis would be nice to have one day.

**Comment by andrewvanbreda** [comment]
Yes, I don't think anyone has updated the species alerts logic to take into account your fix, or did you do that?

**Comment by andrewvanbreda** [comment]
ok sorry, you have done that. If you think it works then I don't have an issue, I haven't done any testing
