### ISSUE TITLE
Tolerance of errors in jpeg files

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/warehouse#27]
The logs on warehouse1 have a number of errors such as:
2015-10-13 16:14:18 +01:00 --- error: #2: Error converted to exception. imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
 at line 76 in file D:\web sites\warehouse1\system\libraries\drivers\Image\GD.php
2015-10-13 16:14:18 +01:00 --- error: Missing i18n entry general_errors.imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
 for language en_GB

The results of this are occurrence_media entries that point to missing files in the upload directory. 

This issue is discussed on the PHP bugs list at https://bugs.php.net/bug.php?id=39918. It appears that errors in the jpeg header might be tolerated by some programs, but PHP throws a warning by default.

So, proposed resolutions:

* Call ini_set("gd.jpeg_ignore_warning", 1) in the code somewhere before we do any image processing.
* Better error handling - if an error does get thrown that we don't handle, don't create the occurrence_media record.

**Comment by johnvanbreda** [comment]
Example - http://www.brc.ac.uk/irecord/record-details?occurrence_id=2610049

**Comment by JimBacon** [comment]
The PHP documentation (http://php.net/manual/en/function.imagecreatefromjpeg.php) gives an example as follows where they use error suppression on the call to imagecreatefromjpeg() followed by error checking.

```
    /* Attempt to open */
    $im = @imagecreatefromjpeg($imgname);

    /* See if it failed */
    if(!$im)
    {
        ...
    }
```
I thought that might be better until I found that the call to imagecreatefromjpeg() is in the Kohana GD Image driver which I'm inclined to leave alone. The ini setting seems very well targeted and a good alternative.

The proposal sounds fine with just one possible amendment that, on error, how about we still create an occurrence_media record but with a 'corrupt image' jpeg so that information such as caption is preserved.

Other thoughts which I'd disregard for now were
1. Could preprocess images to clean them up (http://php.net/manual/en/function.imagecreatefromjpeg.php#65656) although camera information will be interesting to some people.
2. Could switch to ImageMagick library. (http://www.zenphoto.org/support/topic.php?id=9611)

**Comment by johnvanbreda** [comment]
I think although this warning currently prevents the code running which creates the jpeg file, the proposed ini setting will in fact allow the jpeg to be created OK (it is a recoverable error). Therefore a corrupt image jpeg is not required in this instance though it could of course be useful in other scenarios where the image cannot be recovered.
