### ISSUE TITLE
cache_verification tables not being updated

### ISSUE THREAD

**Issue by JimBacon** [Indicia-Team/warehouse#397]
When verification rules are added or updated, the corresponding cache entries should be updated.
This works fine when doing individual records via the web UI.
However, when multiple records are imported from a file, the cache tables are not updated.

This is not working correctly because the current order of events is
 - update verification_rules table
 - update cache_verification table (via the postSubmit method of the model)
 - update verification_rule_metadata table
 - update verification_rule_data table

The cache table is updated based on out of date or missing rule data that comes from the two tables which are only updated afterwards.

**Comment by JimBacon** [comment]
There is more to it than I first thought because, even if a repeat update is performed with all the data is available, the cache is still not populated.
This appears to be because the cache update is happening within a transaction and an error occurs on a subsequent query within the transaction
```
ERROR:  lastval is not yet defined in this session
STATEMENT:  SELECT LASTVAL() AS insert_id
```

**Comment by johnvanbreda** [comment]
@JimBacon when I've seen this error before, it's been because Kohana has interpreted an SQL statement as an insert statement, then tried to access lastval(). In some cases, an insert statement doesn't return lastval(), breaking the transaction, and the subsequent query then fails. Here's an example and slightly hacky remedy: https://github.com/Indicia-Team/warehouse/blob/98f01e375bddcf24d30af91b726b6b0de23a7069/application/models/termlists_term.php#L253

**Comment by JimBacon** [comment]
There is still an issue with importing new rules not getting cached.
