### ISSUE TITLE
Accessing a not existing entry return wrong http status code

### ISSUE THREAD

**Issue by dve** [Indicia-Team/warehouse#41]
When accessing a non existing entity via the data service the return code is 403 instead of 404. This is caused by: https://github.com/Indicia-Team/warehouse/blob/master/modules/indicia_svc_data/controllers/services/data.php#L968 which throws always an AuthorisationError.

Since we support 404 we should also return it in this case.

**Comment by johnvanbreda** [comment]
At the moment, the check_update_access method does not distinguish between a missing record (requested by a specific ID) or a record that exists but you do not have access to. That's why you get an authorisation error. I'm of the opinion that the service should not make this distinction (otherwise you can use the API to sniff for record IDs for records that you should not know exist, even if you can't get to the details). Therefore a suggestion would be that in this case you simply get a record not found error 404, not an authorisation error 403.
Do you agree?

**Comment by dve** [comment]
That's ok with me, but does someone else needs the old behaviour?

**Comment by johnvanbreda** [comment]
Response code 1001 can still be used by other clients so it should be OK to change this. Committed to develop branch.
