### ISSUE TITLE
OID incompatibility PostgreSQL 

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/warehouse#491]
Appreciate i'm working within an untested pgsql version here so not after a resolution but just for if/when you look at testing against pgsql 15. I've found i am missing the summariser_definitions table in the database digging into it the database update failed on this: modules/summary_builder/db/version_0_1_0/201410111800_tables.sql so the table was never created.

Error;
`2023-09-04 15:35:38 +02:00 --- error: Error in file: C:/xampp/htdocs/indicia/modules/summary_builder/db/version_0_1_0/201410111800_tables.sql
2023-09-04 15:35:38 +02:00 --- error: There was an SQL error: ERROR:  tables declared WITH OIDS are not supported - `

Similar messages a posted outside Indica note this as being a result PostgreSQL version incompatibility, with 13 being the last version to support OID's: https://stackoverflow.com/questions/76629159/tables-declared-with-oids-are-not-supported

**Comment by JimBacon** [comment]
A naive comment, since I know nothing about this subject, but if the developer had no need of a primary key on this table and postgres has no need of OIDs on a table any more, can we just remove the WITH (OIDS) from the table declaration?

If you remove that clause then the table will naturally be created okay but the question is then whether the summary builder will operate correctly.

It crops up in the file you mention and also in modules/summary_builder/db/version_2_29_0/201903091200_tables.sql. This query file and all the others in the modules/summary_builder/db subfolders will have been skipped, I think, since the first in the series failed. The system table will hold the last run script for the module to help work out where things are at.

I'm not sure if running the upgrade script again would re-run the queries or whether they would need doing manually.

**Comment by benj-d** [comment]
I think it'll pick up the un-run scripts as it should have run this with the initial installation but failed and i missed it. Only noticing today when i tried to run it via upgrade.php and it picked up this script. I'd considered removing the statements but figured if it's been created then it must be being referenced somewhere else in the code. The second statement seems to be used in the absence of a primary key, presumably we'd still need a key of some kind?

Most of the 'fixes' I've found online seem to relate to replacing it with a sequential integer but i just don't know what else is using it so might be affected.. I could have ago and find out. Currently battling through downgrading from 15 to 13 which is creating it's own barrage of (non-warehouse) issues!

**Comment by benj-d** [comment]
Shall see how it goes but removing both With OID statements allowed the upgrade to run without error. The table now exists in the db and the associated pages on the warehouse appear to work fine...

**Comment by JimBacon** [comment]
A key might not be needed. I don't believe the table joins to any other and selection of records may just depend on WHERE clauses combining various columns. Search for `summary_occurrences` in modules/summary_builder/config/summary_builder.php and you'll see the kind of thing I mean.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda can we remove the WITH OIDS from the CREATE TABLE?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : I don't see why not. I think the table generation SQL was just copied in from pgAdmin, so I've got no strong feelings: I can't see why it would have any effect.

**Comment by JimBacon** [comment]
One day, when we move to a scalable infrastructure and are creating database replicas, very possibly using PostgreSQL >= v15, we will probably need to add a primary key to this table. It would be useful future-proofing to ensure any new table we add to the warehouse has a primary key.

**Comment by johnvanbreda** [comment]
Fixed - see ef92a4454e20f89b86b99f26f43805a22dc90127
